// @ts-check

// The sidebar is generated from the docs/ folder tree. Each subfolder carries a
// `_category_.json` that sets its label and position, so the numbered directory
// names drive the order without being shown to the reader.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "autogenerated",
      dirName: "."
    }
  ]
};

module.exports = sidebars;
